# Generated by Django 6.0.7 on 2026-07-28 11:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='почта')),
                ('name', models.CharField(verbose_name='имя')),
                ('surname', models.CharField(verbose_name='фамилия')),
                ('patronymic', models.CharField(null=True, verbose_name='отчество')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='идентификатор')),
                ('videoUrl', models.URLField(verbose_name='URL видео, которому принадлежит сегмент')),
                ('category', models.IntegerField(choices=[(None, 'Выберите категорию сегмента'), (1, 'Реклама или спонсор видео'), (2, 'Самореклама (услуг или своих интернет-ресурсов)'), (3, 'Напоминание о взаимодействии (лайк, подписка, комментарий)'), (4, 'Пересказ предыдущих видео или рассказ о том, что будет в следующих')], verbose_name='категория сегмента')),
                ('action', models.CharField(choices=[('Пропустить', 'Skip'), ('Заглушить', 'Mute')], default='Пропустить', verbose_name='действия с сегментом')),
                ('start', models.TimeField(verbose_name='начало сегмента')),
                ('end', models.TimeField(verbose_name='конец сегмента')),
                ('votes_amount', models.IntegerField(default=0, verbose_name='кол-во голосов за и против')),
                ('submiter_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='идентификатор загрузившего пользователя')),
            ],
            options={
                'permissions': (('protect_segment', 'Защита сегмента от последующих изменений со стороны рядовых пользователей. Доступно только администраторам или модераторам.'), ('change_category', 'Изменение категории сегмента.'), ('change_action', 'Изменение действия над категорией (заглушение или пропуск).'), ('vote', 'Проголосовать за или против сегмента, таким образом поддержав его от скрытия или наоборот.')),
            },
        ),
    ]
