# Generated by Django 6.0.7 on 2026-07-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccessSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='is_protected',
            field=models.BooleanField(default=False, verbose_name='сегмент защищён модератором или администратором'),
        ),
    ]
