# Generated by Django 6.0.7 on 2026-07-28 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccessSystem', '0002_segment_is_protected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='segment',
            old_name='submiter_id',
            new_name='submiter',
        ),
    ]
