# Generated by Django 6.0.7 on 2026-07-28 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccessSystem', '0003_rename_submiter_id_segment_submiter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='segment',
            old_name='votes_amount',
            new_name='rating',
        ),
    ]
