# Generated by Django 6.0.7 on 2026-07-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccessSystem', '0004_rename_votes_amount_segment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='вес сегмента'),
        ),
    ]
