# Generated by Django 6.0.7 on 2026-07-24 17:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='идентификатор')),
                ('videoUrl', models.URLField(verbose_name='URL видео, которому принадлежит сегмент')),
                ('category', models.IntegerField(choices=[(None, 'Выберите категорию сегмента'), (1, 'Реклама или спонсор видео'), (2, 'Самореклама (услуг или своих интернет-ресурсов)'), (3, 'Напоминание о взаимодействии (лайк, подписка, комментарий)'), (4, 'Пересказ предыдущих видео или рассказ о том, что будет в следующих')], verbose_name='категория сегмента')),
                ('action', models.CharField(choices=[('Пропустить', 'Skip'), ('Заглушить', 'Mute')], default='Пропустить', verbose_name='действия с сегментом')),
                ('start', models.TimeField(verbose_name='начало сегмента')),
                ('end', models.TimeField(verbose_name='конец сегмента')),
                ('votes_amount', models.IntegerField(default=0, verbose_name='Кол-во голосов за и против')),
                ('submiter_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='идентификатор загрузившего пользователя')),
            ],
        ),
    ]
